# General
title: Florescer Desenvolvimento Humano
email: contato@florescer-empresas.com.br
source: .
destination: ./public
baseurl: "/florescer-empresas.com.br"
url: https://medeirosinacio.github.io
srcurl: "/florescer-empresas.com.br"
lang: pt-BR
locale: pt_BR
author: Fernanda Stroff e Isis Couto
description: "Psicólogas clínicas e organizacionais atuando no desenvolvimento humano. Treinamentos, lideranças e saúde mental para empresas que colocam pessoas no centro."
google_analytics: ""
published: true

# Staticforms form contact
staticforms_api_key: b805ad43-5c0a-42f4-bcb7-f08c89da57b3

# Social Media
social:
  name: Florescer Desenvolvimento Humano
  links:
    - https://www.instagram.com/florescer.dh/
    - https://www.linkedin.com/company/florescer-dh/

instagram_url: "https://www.instagram.com/florescer.dh/"
linkedin_url:  "https://www.linkedin.com/company/florescer-dh/"
whatsapp_url:  "https://wa.me/5541999999999"

# Instagrams pessoais
instagram_fernanda: "https://www.instagram.com/fernanda_stroffpsicologia/"
instagram_isis:     "https://www.instagram.com/psicologaisiscouto/"

# Site Paths
post_path:  /assets/images/posts/
icon_path:  /assets/icons/
image_path: /assets/images/
css_path:   /assets/css/
js_path:    /assets/scripts/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tailwindcss
  - assets/css/input.css
  - .idea
  - LICENSE
